name: Lint
on: [push, pull_request]
jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
  # cargo-vet:
  #   name: Vet Dependencies
  #   runs-on: ubuntu-latest
  #   env:
  #     CARGO_VET_VERSION: 0.10.0
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install Rust
  #     run: rustup update nightly && rustup default nightly
  #   - uses: actions/cache@v4
  #     with:
  #       path: ${{ runner.tool_cache }}/cargo-vet
  #       key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
  #   - name: Add the tool cache directory to the search path
  #     run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
  #   - name: Ensure that the tool cache is populated with the cargo-vet binary
  #     run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
  #   - name: Invoke cargo-vet
  #     run: cargo vet --locked
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@nightly
          with:
              components: clippy
        - uses: auguwu/clippy-action@1.4.0
          with:
              token: ${{secrets.GITHUB_TOKEN}}