name: Upgrade deps
on:
  schedule:
    - cron: '0 7 * * 6'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}